layout_spectrum: 0
typography_spectrum: 0.7827303
color:
  saturation: 0.2222222
  brandStrength: 0.6653215
  lightness: 0
  rhythmicContrast: 0.4749104
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: BK Lounge
